// src/entities/doctor/models/mockData.ts
import { Doctor } from '@shared/types';

export const DOCTORS: Doctor[] = [
  {
    id: '1',
    name: 'Иванова Мария Сергеевна',
    specialization: 'Терапевт',
    serviceIds: ['1', '4'],
    experience: '12 лет',
    rating: 4.9,
    reviewsCount: 148,
    initials: 'ИМ',
    avatarColor: '#4A90D9',
    about: 'Специализируется на эстетической реставрации и лечении сложных форм кариеса. Применяет методы минимально инвазивной стоматологии.',
    education: 'МГМСУ им. А.И. Евдокимова, 2010',
  },
  {
    id: '2',
    name: 'Петров Алексей Николаевич',
    specialization: 'Хирург-имплантолог',
    serviceIds: ['2', '5'],
    experience: '18 лет',
    rating: 4.8,
    reviewsCount: 212,
    initials: 'ПА',
    avatarColor: '#E05C5C',
    about: 'Эксперт в области дентальной имплантации и костной пластики. Сертифицированный специалист по системам Nobel Biocare и Straumann.',
    education: 'Первый МГМУ им. И.М. Сеченова, 2005',
  },
  {
    id: '3',
    name: 'Сидорова Елена Викторовна',
    specialization: 'Ортодонт',
    serviceIds: ['3'],
    experience: '9 лет',
    rating: 4.9,
    reviewsCount: 97,
    initials: 'СЕ',
    avatarColor: '#9B59B6',
    about: 'Специалист по исправлению прикуса у детей и взрослых. Работает с брекет-системами и прозрачными элайнерами Invisalign.',
    education: 'РУДН, медицинский факультет, 2014',
  },
  {
    id: '4',
    name: 'Козлов Дмитрий Андреевич',
    specialization: 'Терапевт · Гигиенист',
    serviceIds: ['1', '4', '6'],
    experience: '7 лет',
    rating: 4.7,
    reviewsCount: 83,
    initials: 'КД',
    avatarColor: '#27AE60',
    about: 'Занимается комплексной гигиеной полости рта и профилактикой стоматологических заболеваний. Детский стоматолог с мягким подходом.',
    education: 'СПбГМУ им. И.П. Павлова, 2016',
  },
  {
    id: '5',
    name: 'Новикова Ольга Павловна',
    specialization: 'Ортопед · Протезист',
    serviceIds: ['5'],
    experience: '15 лет',
    rating: 4.8,
    reviewsCount: 176,
    initials: 'НО',
    avatarColor: '#F39C12',
    about: 'Специализируется на эстетическом протезировании: виниры, E.max коронки, безметалловая керамика.',
    education: 'КубГМУ, 2008',
  },
];
